### PR TITLE
Test on Node 10, 12 and latest

### PR DESCRIPTION
**Pull request by DanielRuf**
It seems the builds for 12 and latest fail because of different snapshots.

### CODE REVIEW

**Comment by DanielRuf** [comment]
This is due to the v8 changes affecting `sort()`, for this `localeCompare()` or a custom sorting has to be used.

`Array.sort()` is now basically really stable and it was unstable up to Node 12.

https://v8.dev/blog/array-sort
https://v8.dev/features/stable-sort

```diff
expect(received).toEqual(expected) // deep equality

- Expected
+ Received

  Array [
-   "a;b;e",
-   "a;b;b",
-   "a;b;c",
    "a;b;d",
+   "a;b;c",
+   "a;b;b",
+   "a;b;e",
    "a;b",
    "a",
  ]
```

**Comment by DanielRuf** [comment]
https://travis-ci.org/jlfwong/speedscope/jobs/637907131#L291

This is due to the v8 changes affecting `sort()`, for this `localeCompare()` or a custom sorting has to be used.

`Array.sort()` is now basically really stable and it was unstable up to Node 12.

https://v8.dev/blog/array-sort
https://v8.dev/features/stable-sort

```diff
expect(received).toEqual(expected) // deep equality

- Expected
+ Received

  Array [
-   "a;b;e",
-   "a;b;b",
-   "a;b;c",
    "a;b;d",
+   "a;b;c",
+   "a;b;b",
+   "a;b;e",
    "a;b",
    "a",
  ]
```

**Comment by DanielRuf** [comment]
https://travis-ci.org/jlfwong/speedscope/jobs/637907131#L291

This is due to the v8 changes affecting `sort()`, for this `localeCompare()` or a custom sorting algorithm / custom compare function has to be used.

`Array.sort()` is now basically really stable and it was unstable up to Node 12.

https://v8.dev/blog/array-sort
https://v8.dev/features/stable-sort

```diff
expect(received).toEqual(expected) // deep equality

- Expected
+ Received

  Array [
-   "a;b;e",
-   "a;b;b",
-   "a;b;c",
    "a;b;d",
+   "a;b;c",
+   "a;b;b",
+   "a;b;e",
    "a;b",
    "a",
  ]
```

**Comment by DanielRuf** [comment]
https://travis-ci.org/jlfwong/speedscope/jobs/637907131#L291

This is due to the v8 changes affecting `sort()`, for this `localeCompare()` or a custom sorting algorithm / custom compare function has to be used.

`Array.sort()` is now basically really stable and it was unstable up to Node 12.

https://v8.dev/blog/array-sort
https://v8.dev/features/stable-sort

```diff
expect(received).toEqual(expected) // deep equality

- Expected
+ Received

  Array [
-   "a;b;e",
-   "a;b;b",
-   "a;b;c",
    "a;b;d",
+   "a;b;c",
+   "a;b;b",
+   "a;b;e",
    "a;b",
    "a",
  ]
```

**Comment by DanielRuf** [comment]
See https://github.com/moment/moment-timezone/pull/762 for example.

The rest of the failing tests seem to be because of the differences in the tracing and performance of NodeJS >= 12.

**Comment by jlfwong** [comment]
Iiiinteresting. Thanks! I'll check out the branch sometime in the next few weeks and see if I can work through the sources of the issues. Thanks for the diagnosis and links to references!

**Comment by jlfwong** [comment]
Closing this since it's superseded by #263.

Thanks again for filing this and explaining the sort stability issue -- it probably would've taken me a very long time to figure out root cause without the explanation!

**Pull request closed without merging**
