### PR TITLE
Support importing partial JSON files

### PR DESCRIPTION
**Pull request by loganek**
Partial files are allowed in many specs, e.g. Trace Event Format,
so the viewer should be able to load partial files as well.

### CODE REVIEW

**Comment by loganek** [comment]
Hey @jlfwong , could you please review that change? Thanks!

**Comment by jlfwong** [comment]
@loganek Hi! My home internet has been down for the last week, but I'll try to get to this soon!

I'm generally wary of adding third party dependencies, but I took a look at `partial-json-parser`, and it looks like it has no dependencies and is enough code that I'd rather not just do it myself, so I'm happy to accept this.

I'll try to take a closer look later this week, merge if I don't find anything concerning, then do a release that picks this up.

Out of curiousity, were you motivated to do this because you have Chrome trace profiles that are not terminated? What was generating them?

**Comment by loganek** [comment]
@jlfwong So sorry, I didn't want to rush you at all! Just thought that you missed the PR, so wanted to ping you, but please take your time, it's not super urgent for me.

Yeah, I wasn't sure what's your opinion about third party dependencies, but since it wasn't very time consuming, I decided to give a try.

Yes, I did this PR exactly because my files are not terminated; those files are generated by hawktracer-converter (https://github.com/loganek/hawktracer-converter/) which is a client app of my profiler (https://github.com/amzn/hawktracer). I guess I could work-around this in the converter to close the file properly, but since the format specification allow to have non-terminated files, I thought it'd be more correct to fix your viewer instead.

Btw. great tool, it feels much faster than the one embedded to chrome, and flamegraphs is a nice feature too. Good job, and thanks for doing that :)

**Comment by jlfwong** [comment]
This is great as is :) Thanks for taking the time to carefully craft this PR!

**Comment by jlfwong** [comment]
@loganek Ah... sorry I spoke too soon. I had to revert the commit because `partial-json-parser` doesn't guarantee termination: https://github.com/rgovind92/partial-json-parser/issues/3

**Pull request merged**
