### PR TITLE
Improve hermes profile frame keys to better group frames

### PR DESCRIPTION
**Pull request by zacharyfmarion**
Because all args are serialized in the key for hermes profiles, frames were not properly getting grouped since the "parent" property was different. This PR ensures that the frame key is properly constructed from the function name, file name, line + column number.

| Before | After |
| ----- | ----- |
| Screenshot 2023-12-27 at 2 25 32 PM | Screenshot 2023-12-27 at 2 26 02 PM |
| Screenshot 2023-12-27 at 2 13 37 PM | Screenshot 2023-12-27 at 2 14 20 PM |

### CODE REVIEW

**Comment by zacharyfmarion** [comment]
@jlfwong one more for you before we start thinking about communicating this out 😅

**Comment by jlfwong** [comment]
Looks good! If you update the PR name to give this a more descriptive name for the commit log, I'll merge

**Comment by zacharyfmarion** [comment]
@jfwong updated, I always miss something 😃

**Comment by jlfwong** [comment]
@zacharyfmarion you also fix things so fast it doesn't matter much 😄

**Comment by jlfwong** [comment]
Published as v1.19.0 and deployed to https://www.speedscope.app/

**Pull request merged**
