### PR TITLE
Unpin dev dependencies and address build failures

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This change adds the `^` range specifier for many dev dependencies. The only exception is TypeScript, which likes to make breaking changes in semver minor releases.  I noticed that this projects doesn't build on Node.js 13.x, largely due to out of date dependencies.  This felt like a good first step to start upgrading dev dependencies one by one.

Note: the vast majority of changes here are either in `package-lock.json` or a result of running `npm run prettier`.

### CODE REVIEW

**Comment by jlfwong** [comment]
Hi @JustinBeckwith!

> This change adds the ^ range specifier for many dev dependencies. The only exception is TypeScript, which likes to make breaking changes in semver minor releases. I noticed that this projects doesn't build on Node.js 13.x, largely due to out of date dependencies. This felt like a good first step to start upgrading dev dependencies one by one.

Can you explain a bit of the motivation for this? I strongly prefer to pin dependencies, especially dev dependencies for projects that aren't usable as libraries because it alleviates an entire class of reproducibility problems. It's really common for things that weren't intended to be breaking changes to be accidentally breaking changes, resulting in different installations happening on different people's machines (or even multiple machines where I'm running on both).

Bumping versions because of node incompatibility sounds fine to me, but I'd rather bump from pinned versions to pinned versions.

I understand the need for libraries which things directly depend upon to avoid version pinning to prevent massive duplication of similarly versioned packages and to pick up security fixes automatically, but neither of those are relevant for speedscope.

**Comment by JustinBeckwith** [comment]
Greetings!  And thanks for the really thoughtful reply.  Just to be clear, whatever approach you want to take here is great, and there are no wrong answers.  You made a lovely thing, and I'd like to use it with a later version of node.js.  To share a little on why I general recommend folks go down the path of `^`....

The saving grace here is `package-lock.json`.   That file ensures the tree of transitive dependencies is locked for users that clone the repository.  Without doing something the explicitly would update the versions in that lock file, everyone _should_ be working from the same locked tree of top level and transitive dependencies.  This has no effect on the packages in the shipped module.  The benefit is you get to accept bug fixes, security fixes, and features of libraries as they come out.   I suspect you would still be just as safe due to the lock file.  

Either way to decide to go - I do really like having a bot bump my dependencies for me (see #260).  If you decide to keep dev dependencies pinned down, tools like [renovate](https://github.com/renovatebot/renovate) can automatically submit PRs to bump them for you as updates come up.  With pinned dependencies, the volume of those updates could be pretty high, so you can even set it up to automerge PRs in particular situations (dev deps only, CI passes, patch only, etc).

Just to make sure I don't lose the forest through the trees - the entire goal was to start inching towards supporting later versions of node.js.  I tried to clone this repo, and `npm install` fails on the latest build of node.js 13.  The reason turned out to be an old pinned build of `jest`, which had an old version of `fs-events`, which was struggling to do some sort of native compilation.  The problem went away if I upgraded to the latest version of `jest`.  

P

**Comment by JustinBeckwith** [comment]
Also - Apologies if it seemed like I jumped straight to solutions without filing the original root issue.  Thanks :)
https://github.com/jlfwong/speedscope/issues/262

**Comment by jlfwong** [comment]
Thanks for filing #262! I'll see if I can try to fix that later today (possibly by merging something really similar to this PR). The specific context around jest is helpful.

Re: "The saving grace here is package-lock.json"

What happens when you manually bump one of the versions of something in `package.json`? Will the existence of `package-lock.json` ensure that *only* the version of something whose explicit version string was changed is updated, or may it also look for newer versions of packages with `^` or similar modifiers marked?

In any case, I find reasoning about the effects of changing `package.json` to be much easier with locked versions. `package-lock.json` is definitely helpful nonetheless to pin transitive dependencies (I've been in situations before where a coworker had a broken build despite all direct dependencies matching because of a version mismatch on a transitive dependency).

Thanks for the patient explanations, and thanks for cloning speedscope and trying to build it locally and letting me know it's busted on Node 13! I'm curious to know what you're trying to modify if you can share.

**Comment by JustinBeckwith** [comment]
On bumping something in `package.json` - after you bump it, and run `npm install`, it will go through the whole package resolution process.  It will attempt to update the top level package, and only _if needed_ bump transitive dependencies if allowed within range.  There's a big complicated range resolution algorithm that has to find the highest common denominator across given ranges.  

On what I'm doing - of course!  A couple of years ago I wrote a thingy that lets you track the require time of a given npm module:
- https://npmtrace.appspot.com/
- https://github.com/JustinBeckwith/npmtrace/

It used the now-defunct trace viewer from chrome dev tools:
- https://github.com/catapult-project/catapult

A few weeks ago, after a chrome update, it just, stopped working.  I needed to get in and try updating to the latest version, but then I found this and figured why not 🤷   I like that this project lives on GitHub, is written in TypeScript, and looks to be pretty well maintained.  

So what I'd really like to do is pick up the trace viewer as a component, and have an API to load a trace directly given the JSON.  I have the backend service that does all the tracing and storage and API and such, I really just need to visualize it within my app.  
 

I have no idea what specifically I was going to try and change; I got distracted when I couldn't run `npm install` the first time 😆

**Comment by jlfwong** [comment]
> A couple of years ago I wrote a thingy that lets you track the require time of a given npm module:

Cool!

> So what I'd really like to do is pick up the trace viewer as a component, and have an API to load a trace directly given the JSON. I have the backend service that does all the tracing and storage and API and such, I really just need to visualize it within my app.

Gotcha!

There are two mechanisms that might be interesting to you to do this. One that exists and one that I'm open to. The easiest is if you have a file that can be served from a URL, then you can specify the profile URL like so: https://github.com/jlfwong/speedscope#importing-via-url

The one that I'm open to is to use speedscope as a library. The discussion for that is taking place in #16.

**Pull request closed without merging**
