### PR TITLE
Replace fuzzy search with regex matching

### LINKED ISSUE #352: Search for occurences of whole word.
Hi! 

Thank you very much for this outstanding and powerful tool, which makes my life much easier and more productive! :) I'm using speedscope from some time and currently I have a feeling that its built-in search functionality is not searching for whole words, which is quite unusual for me. Seems to me that it's enough that the respective letters constituting the word I'm searching for are present to be counted as an occurrence. 

image

How can I make the search engine to search for whole words? If that's not possible could you kindly add such feature please?

### PR DESCRIPTION
**Pull request by lucymcphail**
Remove the fuzzy search as suggested in https://github.com/jlfwong/speedscope/issues/352#issuecomment-1123072274.

Closes #352.

### CODE REVIEW

**Comment by AloisKraus** [comment]
When will this be merged?

**Comment by jes2ica** [comment]
Any updates on this? We are really looking forward to this feature!

**Comment by jlfwong** [comment]
Hi! Sorry the slow movement here. See https://github.com/jlfwong/speedscope/issues/352#issuecomment-1278425316

**Comment by jlfwong** [comment]
Hey all, thank you for contributing this -- it helped nudge me to get this done. This was ultimately superseded by #407

**Pull request closed without merging**
